language: cpp

os:
  - linux
  - osx

env:
  - CONFIG=Debug
  - CONFIG=Release

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
      && sudo apt-add-repository -y ppa:beineri/opt-qt541
      && sudo apt-get -qq update
      && sudo apt-get install -qq build-essential libssl-dev pkg-config
      && sudo apt-get -qq install g++-4.8 libc6-i386 qt54tools qt54svg qt54multimedia qt54declarative qt54quick1 qt54quickcontrols qt54translations qt54imageformats 
      && git clone https://github.com/google/protobuf.git
      && cd protobuf
      && git checkout v2.6.1
      && ./autogen.sh
      && ./configure
      && make
      && make check
      && sudo make install
      && cd ..
      && sudo ldconfig
      && export CXX="g++-4.8"
      && export CC="gcc-4.8"
      && sudo apt-get -f install
      && sudo apt-get install -qq tor
      ;
    else
         brew update
      && brew install qt5
      && brew install protobuf
      && chmod -R 755 /usr/local/opt/qt5/*
      ;
    fi

script:
  - /opt/qt54/bin/qt54-env.sh 
  - /opt/qt54/bin/qmake ricochet.pro CONFIG+=$CONFIG
  - make