set(CMAKE_SYSTEM_NAME Windows CACHE STRING "" FORCE)
set(CMAKE_SYSTEM_PROCESSOR x86_64 CACHE STRING "" FORCE)

set(CMAKE_PREFIX_PATH "/var/tmp/dist/mingw-w64/x86_64-w64-mingw32/lib/" CACHE STRING "" FORCE)
