Document: ricochet-refresh
Title: Debian ricochet-refresh Manual
Author: <insert document author here>
Abstract: This manual describes what ricochet-refresh is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ricochet-refresh/ricochet-refresh.sgml.gz

Format: postscript
Files: /usr/share/doc/ricochet-refresh/ricochet-refresh.ps.gz

Format: text
Files: /usr/share/doc/ricochet-refresh/ricochet-refresh.text.gz

Format: HTML
Index: /usr/share/doc/ricochet-refresh/html/index.html
Files: /usr/share/doc/ricochet-refresh/html/*.html
